# https://opentdb.com/api_config.php

question_data = [
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
      "question": "Igneous rocks are formed by excessive heat and pressure.", "correct_answer": "False",
      "incorrect_answers": ["True"]}, {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                                       "question": "In Norse mythology, Thor once dressed as a woman.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "History", "type": "boolean", "difficulty": "easy",
      "question": "The Spitfire originated from a racing plane.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In &quot;Mario Kart 64&quot;, Waluigi is a playable character.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "Faust is a playable character in &quot;Guilty Gear Xrd Revelator&quot;.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.", "correct_answer": "False",
      "incorrect_answers": ["True"]}, {"category": "Sports", "type": "boolean", "difficulty": "easy",
                                       "question": "Peyton Manning retired after winning Super Bowl XLIX.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "&quot;Half-Life 2&quot; runs on the Source Engine.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Animals", "type": "boolean", "difficulty": "easy",
      "question": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
      "question": "In Pok&eacute;mon, Ash&#039;s Pikachu refuses to go into a pokeball.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
      "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
      "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
      "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In the game Dead by Daylight, the killer Michael Myers is refered to as &quot;The Shape&quot;.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In Terraria, you can craft the Cell Phone pre-hardmode.", "correct_answer": "True",
      "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                        "question": "California is larger than Japan.",
                                        "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Sports", "type": "boolean", "difficulty": "easy",
      "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Animals", "type": "boolean", "difficulty": "easy",
      "question": "Cats have whiskers under their legs.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
      "question": "&quot;Minions&quot; was released on the June 10th, 2015.", "correct_answer": "False",
      "incorrect_answers": ["True"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
      "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
      "question": "Psychology is the science of behavior and mind.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
      "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Sports", "type": "boolean", "difficulty": "easy",
      "question": "There are a total of 20 races in Formula One 2016 season.", "correct_answer": "False",
      "incorrect_answers": ["True"]}
]
